<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

abstract class BaseModel extends Model
{
    public abstract function validationRules();

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $user = \auth()->user();
        self::created(function ($model) use ($user) {
            if (!is_null($user)) {
                $model->created_by = $user->id;
            }
        });
        self::updated(function ($model) use ($user) {
            if (!is_null($user)) {
                $model->updated_by = $user->id;
            }
        });
    }

    public function userCreatedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, "created_by", "id");
    }

    public function userUpdatedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, "updated_by", "id");
    }
}
